/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_learning;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author singh
 */
public class Lecture_detail extends javax.swing.JFrame {

    /**
     * Creates new form Lecture_detail
     */
    int lecture_id;
    public Lecture_detail(int id) {
        initComponents();
        setSize(500,500);
        lecture_id=id;
        details();
       
    }
    void details()
    {
      System.out.println(lecture_id);
        String ans=myClient.fetchdetail(lecture_id);
         StringTokenizer st = new StringTokenizer(ans, "$");

                 
         
        int id = Integer.parseInt(st.nextToken());
        String name1 = st.nextToken();
        String description1 = st.nextToken();
        String duration = st.nextToken();
        String photo = st.nextToken();
        int course_id = Integer.parseInt(st.nextToken());
        String trailer1 = st.nextToken();
        String video1 = st.nextToken();

        ImageIcon ic = new ImageIcon(photo);

        Image img = ic.getImage().getScaledInstance(poster.getWidth(), poster.getHeight(), Image.SCALE_SMOOTH);

        ImageIcon ic1 = new ImageIcon(img);

        poster.setIcon(ic1);

        name.setText(name1);

        description.setText(description1);
        
        //add actionlistener on play trailer button
        trailer.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    URI uri=new URI("https://www.youtube.com/watch?v="+trailer1);
                    Desktop d=Desktop.getDesktop();
                    d.browse(uri);
                    
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            
        });
        
         Lecture.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                   File f=new File(video1);
                    Desktop d=Desktop.getDesktop();
                    d.open(f);
                    
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            
        });
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poster = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        trailer = new javax.swing.JButton();
        Lecture = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(poster);
        poster.setBounds(30, 20, 190, 340);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 90, 27);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(260, 40, 190, 40);

        jLabel2.setText("Description");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 90, 130, 27);

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 130, 230, 80);

        trailer.setText("Play Trailer");
        getContentPane().add(trailer);
        trailer.setBounds(260, 230, 200, 50);

        Lecture.setText("Play Lecture");
        getContentPane().add(Lecture);
        Lecture.setBounds(260, 310, 200, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecture_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecture_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecture_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecture_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecture_detail(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lecture;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel poster;
    private javax.swing.JButton trailer;
    // End of variables declaration//GEN-END:variables
}
