
package e_learning;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author singh
 */
public class Lectures extends javax.swing.JFrame {

    /**
     * Creates new form Lectures
     */
    int course_id;
    public Lectures(int id) {
        initComponents();
        setSize(500,500);
        course_id=id;
        load_lecture();
    }
    void load_lecture()
    {
       String ans=myClient.fetchlectures(course_id);
    //System.out.println(ans+"in Lecture");
  StringTokenizer st=new StringTokenizer(ans,";;");
        int n=st.countTokens();
        JButton arr[]=new JButton[n];
       int x=10;
       int y=10;
        for(int i=0;i<n;i++)
        {
            String row=st.nextToken();
            StringTokenizer st1=new StringTokenizer(row,"$");
            int id=Integer.parseInt(st1.nextToken());
            String name=st1.nextToken();
            String photo=st1.nextToken();
            arr[i]=new JButton(name);
            arr[i].setBounds(x, y, 200, 100);
            //create image icon and resize it 
            ImageIcon ic=new ImageIcon(photo);
            Image img=ic.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            ImageIcon ic1=new ImageIcon(img);
            //seticon on button
            arr[i].setIcon(ic1);
            arr[i].addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    Lecture_detail obj=new Lecture_detail(id);
                    obj.setVisible(true);
                    dispose();
                }
                
            });
             if(x<210)
            {
                x=x+200;
                System.out.println("-->"+x);
                System.out.println("-->"+name);
            }
            else{
                System.out.println("-->"+x);
                System.out.println("-->"+name);
                x=10;
                y=y+100;
            }
            
             mainpanel1.add(arr[i]);
            mainpanel1.repaint();
        }
        mainpanel1.setPreferredSize(new Dimension(420,y+100));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout mainpanel1Layout = new javax.swing.GroupLayout(mainpanel1);
        mainpanel1.setLayout(mainpanel1Layout);
        mainpanel1Layout.setHorizontalGroup(
            mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        mainpanel1Layout.setVerticalGroup(
            mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainpanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 40, 430, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lectures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lectures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lectures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lectures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lectures(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainpanel1;
    // End of variables declaration//GEN-END:variables
}
