/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_learning;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author singh
 */
public class Manage_categories extends javax.swing.JFrame {

    /**
     * Creates new form Manage_categories
     */
    File ph;
    JFileChooser jfc;
    
    ArrayList<category> al=new ArrayList<>();
    
    myTableModel tm;
    public Manage_categories() {
        initComponents();
        setSize(800, 500);
        /*
        set the name of attributes of table
        
        */
       
        
        
        load_category();
        tm=new myTableModel();
        jTable1.setModel(tm);
        
        jTable1.getColumnModel().getColumn(0).setHeaderValue("NAME");
       jTable1.getColumnModel().getColumn(1).setHeaderValue("PATH");
        jTable1.getTableHeader().repaint();
    }
    void load_category()
    {
        al.clear(); //to show data in table one time to make al empty
        String ans=myClient.fetchCat();
        System.out.println(ans);
        StringTokenizer st=new StringTokenizer(ans,";;");
         while(st.hasMoreTokens())
         {
             String row=st.nextToken();
             StringTokenizer st1=new StringTokenizer(row,"$");
             String name=st1.nextToken();
             String photo=st1.nextToken(); 
             al.add(new category(name,photo));
         }
    }
    class myTableModel extends AbstractTableModel
    {

        @Override
        public int getRowCount() {
           return al.size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
           if(columnIndex==0)
           {
               return al.get(rowIndex).name;
           }
           else{
                return al.get(rowIndex).photo;

           }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        photolb = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Categories");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(18, 6, 765, 47);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Categories");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 370, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("View Categories");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 70, 400, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 120, 340, 250);

        jLabel4.setText("Category Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 107, 160, 40);

        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        getContentPane().add(category);
        category.setBounds(30, 150, 310, 40);

        jLabel5.setText("Photo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(33, 220, 60, 40);

        photolb.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(photolb);
        photolb.setBounds(110, 220, 130, 140);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 250, 120, 50);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 390, 110, 50);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 390, 110, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jfc=new JFileChooser();
        int ans=jfc.showOpenDialog(this);
        
        if(ans==JFileChooser.APPROVE_OPTION)
        {
            ph=jfc.getSelectedFile();
            ImageIcon ic=new ImageIcon(ph.getPath());// imageicon will have to pass the path not file(ph)
            // after resize it
            Image img=ic.getImage().getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
            // make new imageicon bez img not apply on label
            ImageIcon ic1=new ImageIcon(img);
            photolb.setIcon(ic1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String category1=category.getText();
        String ans=myClient.addCategories(category1, ph);
        if(ans.trim().equals("success"))
        {
            JOptionPane.showMessageDialog(rootPane, "Added Successfully");
            category.setText("");
            photolb.setIcon(null);
            load_category();
            tm.fireTableDataChanged();//it is use for when i add new entry in the table it will reflect change in the database on the gui table

        }
        else{
            JOptionPane.showMessageDialog(rootPane, ans);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            int ans=jTable1.getSelectedRow();
            if(ans==-1)
            {
                JOptionPane.showMessageDialog(rootPane, "Please Select The Row");
            }
            else
            {
                String ans1=myClient.deletecat(al.get(ans).name);
                if(ans1.trim().equals("Success"))
                {
                   JOptionPane.showMessageDialog(rootPane, "Row Deleted Successfully");
                   load_category();
                   tm.fireTableDataChanged();
                }
                else
                {
                   JOptionPane.showMessageDialog(rootPane, "Abort");
                    
                }
            }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField category;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
